# Run flutter gen-l10n  to generate
# Run flutter gen-l10n --help to display options
arb-dir: lib/localization
template-arb-file: app_en.arb
output-localization-file: app_localizations.g.dart
output-dir: lib/localization
output-class: AppLocalizations
synthetic-package: false
untranslated-messages-file: missing-translations.txt
preferred-supported-locales: en
nullable-getter: true