
name: CI Workflow
on:
  push:
    branches: [main, rewrite]
  pull_request:
    branches: [dev]
jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version
    - run: flutter pub get
    #- run: flutter test
    # build debug version for now until automated signing is in place:
    - run: flutter build apk --debug
  apple:
    name: Build iOS
    runs-on: macos-13 # required for xcode 15, macos-latest does not yet support it, compare https://github.com/maxim-lobanov/setup-xcode/issues/73
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.1'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        #architecture: x64
    - run: flutter --version
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build ios --release --no-codesign
