
name: CI Workflow
on:
  push:
    branches: [main, rewrite]
  pull_request:
    branches: [main]
jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Decode Keystore and Create key.properties
      env:
          PROPERTIES_PATH: ${{ github.workspace }}/android/key.properties
          STORE_PATH: ${{ github.workspace }}/android/keystore.jks
      run: |
        echo keyPassword=\${{secrets.PLAY_UPLOAD_KEY_PASSWORD}} > ${{env.PROPERTIES_PATH}}
        echo storePassword=\${{secrets.PLAY_UPLOAD_STORE_PASSWORD}} >> ${{env.PROPERTIES_PATH}}
        echo keyAlias=\${{secrets.PLAY_KEY_ALIAS}} >> ${{env.PROPERTIES_PATH}}
        echo storeFile=\${{env.STORE_PATH}} >> ${{env.PROPERTIES_PATH}}
        echo "${{ secrets.PLAY_UPLOAD_KEYSTORE }}" | base64 --decode > ${{env.STORE_PATH}}
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk --release --dart-define GIPHY_API_KEY=${{ secrets.GIPHY_API_KEY }} --dart-define OAUTH_GMAIL=${{ secrets.OAUTH_GMAIL }} --dart-define OAUTH_OUTLOOK=${{ secrets.OAUTH_OUTLOOK }}

  apple:
    name: Build iOS
    runs-on: macos-13 # required for xcode 15, macos-latest does not yet support it, compare https://github.com/maxim-lobanov/setup-xcode/issues/73
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.1'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        #architecture: x64
    - run: flutter --version
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build ios --release --no-codesign
