
name: CI Workflow
on:
  push:
    branches: [main, rewrite]
  pull_request:
    branches: [dev]
jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
    - name: Decode Keystore and Create key.properties
      env:
          ENCODED_STRING: ${{ secrets.PLAY_UPLOAD_KEYSTORE }}
          PROPERTIES_PATH: ${{ github.workspace }}/android/key.properties
      run: |
          TMP_KEYSTORE_FILE_PATH="${{ github.workspace }}/android/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/google_play_upload.jks
          echo keyPassword=\${{ secrets.PLAY_UPLOAD_KEY_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.PLAY_UPLOAD_STORE_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.PLAY_KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo storeFile=\${TMP_KEYSTORE_FILE_PATH}/google_play_upload.jks >> ${{env.PROPERTIES_PATH}}
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk --release

  apple:
    name: Build iOS
    runs-on: macos-13 # required for xcode 15, macos-latest does not yet support it, compare https://github.com/maxim-lobanov/setup-xcode/issues/73
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.1'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        #architecture: x64
    - run: flutter --version
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build ios --release --no-codesign
